### ISSUE TITLE
Slow mode seems broken

### ISSUE THREAD

**Issue by SoniEx2** [kotborealis/VVVVVVwasm#12]
Slow mode (accessibility feature) doesn't seem to be doing anything for me.

**Comment by kotborealis** [comment]
In original version. slow mode controls directrly controls FPS:
https://github.com/kotborealis/VVVVVVwasm/blob/46bf1ba1ad55dae466fb5e5eb3e4edb206c0f860/src/main.cpp#L174

Currently, FPS controlled by `emscripten_main_loop`:
https://github.com/kotborealis/VVVVVVwasm/blob/46bf1ba1ad55dae466fb5e5eb3e4edb206c0f860/src/main.cpp#L278

I'l try to fix this using `emscripten_set_main_loop_timing` (https://emscripten.org/docs/api_reference/emscripten.h.html#c.emscripten_set_main_loop_timing)
